; ================================================================================
; Sprite DPLCs - generated by Flex 2 Sat Dec 26 2020 00:10:16 GMT+0300 (Moscow Standard Time)
; ================================================================================

DPLC_SSWalls:
	dc.w DPLC_SSWalls_0-DPLC_SSWalls, DPLC_SSWalls_1-DPLC_SSWalls
	dc.w DPLC_SSWalls_2-DPLC_SSWalls, DPLC_SSWalls_3-DPLC_SSWalls
	dc.w DPLC_SSWalls_4-DPLC_SSWalls, DPLC_SSWalls_5-DPLC_SSWalls
	dc.w DPLC_SSWalls_6-DPLC_SSWalls, DPLC_SSWalls_7-DPLC_SSWalls
	dc.w DPLC_SSWalls_8-DPLC_SSWalls, DPLC_SSWalls_9-DPLC_SSWalls
	dc.w DPLC_SSWalls_A-DPLC_SSWalls, DPLC_SSWalls_B-DPLC_SSWalls
	dc.w DPLC_SSWalls_C-DPLC_SSWalls, DPLC_SSWalls_D-DPLC_SSWalls
	dc.w DPLC_SSWalls_E-DPLC_SSWalls, DPLC_SSWalls_F-DPLC_SSWalls
DPLC_SSWalls_0: dc.b $1
	dc.b $80, $0
DPLC_SSWalls_1: dc.b $1
	dc.b $F0, $9
DPLC_SSWalls_2: dc.b $1
	dc.b $F0, $19
DPLC_SSWalls_3: dc.b $1
	dc.b $F0, $29
DPLC_SSWalls_4: dc.b $1
	dc.b $F0, $39
DPLC_SSWalls_5: dc.b $1
	dc.b $F0, $49
DPLC_SSWalls_6: dc.b $1
	dc.b $F0, $59
DPLC_SSWalls_7: dc.b $1
	dc.b $F0, $69
DPLC_SSWalls_8: dc.b $1
	dc.b $F0, $79
DPLC_SSWalls_9: dc.b $1
	dc.b $F0, $89
DPLC_SSWalls_A: dc.b $1
	dc.b $F0, $99
DPLC_SSWalls_B: dc.b $1
	dc.b $F0, $A9
DPLC_SSWalls_C: dc.b $1
	dc.b $F0, $B9
DPLC_SSWalls_D: dc.b $1
	dc.b $F0, $C9
DPLC_SSWalls_E: dc.b $1
	dc.b $F0, $D9
DPLC_SSWalls_F: dc.b $1
	dc.b $F0, $E9
	even